version: "3.8"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:8.0
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hamzalatki
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      resources:
        limits:
          memory: 512M
